language: python
python:
- '2.7'
branches:
  except:
  - gh-pages
install:
- pip install -r requirements.txt
script:
- git clone https://github.com/getpelican/pelican-plugins.git official_plugins
- git clone https://github.com/glasslion/pelican-zha.git ../pelican-zha
after_success:
- make github_travis
env:
  global:
    secure: "XeSSCP0+2jC75KyRtQsxK3EpLyusY42MZvvy9S9suz3rushftCs+DWqINs+m5Of0GMhrpam0gJi7e6Y//yCWlBDXcGpaK6kRWHWTJwaIVj+Q8To+rQAb2Vm7Z7/xATNY2leMKyWblVBaDu+hcoB5xu7JYN5rWRluF0jsACCcCSU="
